# True color support
set -g default-terminal "xterm-256color"
#set -ag terminal-overrides ",xterm-256color:RGB"

# プレフィックスキーをC-tに変更
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# マウス操作を有効化
set -g mouse on

set -g set-titles on
set -g set-titles-string "#T"

# viのキーバインドでコピーモード
setw -g mode-keys vi

set -g status-bg blue
set -g status-fg black

# prefix keyが押されたときにステータスバーの色を変更
setw -g window-status-current-format '#[bg=colour2,fg=colour255] #I #W '
# Prefix 押下時にステータスバーを一時的に変える
set -g status-left '#{?client_prefix,#[bg=colour129] PREFIX #[default],}'
set -g status-left-length 20

# neovimのため
set-option -sg escape-time 0
#set-option -g focus-events on

set -s copy-command "xsel --clipboard --input"
# # copy-pipe と競合する場合があるので無効化
# set -s set-clipboard off
